# Generated by Django 2.2.3 on 2019-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0003_student_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slika',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
